language: ruby
cache: bundler
rvm:
  - 2.2.3
env:
  - DB=postgresql

before_script:

  - psql -c 'create database pooka_test' -U postgres

script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec

addons:
  code_climate:
    repo_token: 92f4e1ee499185c542ceb357e658035169180897d5f075939b56f7a72b6d4f9e
